name: Build and Release for POSIX

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Set up build environment
        if: matrix.os == 'macOS-latest'
        run: brew install gcc

      - name: Build project
        run: make

      - name: Create release directory
        run: mkdir -p release

      - name: Copy executable to release directory
        run: cp bin/personalpilot release/personalpilot-${{ matrix.os }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: personalpilot_${{ matrix.os }}
          path: release
