name: Build and Release for Windows

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        if: matrix.os == 'windows-latest'
        run: choco install mingw

      - name: Build project

        run: mingw32-make

      - name: Create release directory
        run: mkdir -p release

      - name: Copy executable to release directory
        run: cp bin/personalpilot.exe release/personalpilot-windows.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: personalpilot_${{ matrix.os }}
          path: release
