name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up build environment
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y g++

      - name: Set up build environment
        if: matrix.os == 'macOS-latest'
        run: brew install gcc

      - name: Set up build environment
        if: matrix.os == 'windows-latest'
        run: choco install mingw

      - name: Build project
        run: |
          if [ "${{ matrix.os }}" != "windows-latest" ]; then
            make
          else
            mingw32-make
          fi

      - name: Package artifacts
        run: |
          mkdir -p release
          if [ "${{ matrix.os }}" != "windows-latest" ]; then
            cp bin/personalpilot ../release/personalpilot-${{ matrix.os }}
          else
            cp bin/personalpilot.exe ../release/personalpilot-windows.exe
          fi
        working-directory: ${{ github.workspace }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: executables
          path: release
